#CountyTitles v1.2.0 (RELEASE) - by Brennan Cheatwood (Copyright 2025)
#This plugin is a simple tool for managing regions and their titles in Minecraft.
#This plugin is highly experimental and may not work as intended. Use at your own risk.
#Tested on Minecraft 1.21.4 running Paper 1.21.4

regions: